#!/usr/bin/env python
"""
     This module will provide dictionary of quotes from Dark Souls NPCs to pull from.
"""

QUOTES = {
    'Solaire of Astora' : ['Oh, hello there.',
        'Oh, hello there.',
        '… You have done well, indeed you have.',
        'You\'ve a strong arm, strong faith, and most importantly, a strong heart.',
        'I am in awe, really.',
        'What do you think? Why not join me, as a warrior of the Sun?',
        'Righteous knights, guardians of all that is good, ' \
            'in the name of the Lord of Sunlight!',
        'Exhilarating, is it not? The power of the Sun!',
        'I am blessed to have found such a brave companion!',
        'Hah hah hah!',
        'Hmm! Ah, oh… hello there.',
        'Forgive me, I was just pondering… about my poor fortune.',
        'I did not find my own sun, not in Anor Londo, nor in Twilight Blighttown.',
        'Where else might my sun be? Lost Izalith, or the Tomb of the Gravelord… ?',
        'But I cannot give up. I became Undead to pursue this!',
        'But when I peer at the Sun up above, it occurs to me…',
        'What if I am seen as a laughing stock, as a blind fool without reason?',
        'Well, I suppose they wouldn\'t be far off!',
        'Oh, there you are.',
        'You\'ve been quiet these days.',
        'Smooth summoning out there?',
        'Anytime you see my brilliantly shining signature, ' \
            'do not hesitate to call upon me.',
        'You\'ve left me with quite an impression. I would relish ' \
            'a chance to assist you.',
        'You really are fond of chatting with me, aren\'t you?',
        'If I didn\'t know better, I\'d think you had feelings for me!',
        'Oh, no, dear me. Pretend you didn\'t hear that!',
        'After all this searching, I still cannot find it…',
        'Was it all a lie? Have I done this all, for nothing?',
        'Oh, my dear sun… What now, what should I do…?',
        '… My sun, my dear, dear sun…',
        '… Finally, I have found it, I have!…',
        '… My very own sun… I am the sun!…',
        '…I\'ve done it… I have…',
        '… My sun… it\'s setting…',
        'A Warrior of the Sun will not just sit and take it!'
        ]
}
